CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "Arguments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(300) NOT NULL,
        "RawText" text NOT NULL,
        "Status" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "SubmittedBy" character varying(100),
        CONSTRAINT "PK_Arguments" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "CollaborativeSessions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "ParticipantIdsJson" text NOT NULL,
        "ContributedArgumentIdsJson" text NOT NULL,
        "MergedNodeIdsJson" text NOT NULL,
        "Status" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ConcludedAt" timestamp with time zone,
        "JointConvergenceMapId" integer,
        "ConsolidatedReportJson" text,
        "ExecutiveSummary" text,
        CONSTRAINT "PK_CollaborativeSessions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "CommonUnderstandingNodes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Text" text NOT NULL,
        "NormalizedKey" character varying(500) NOT NULL,
        "Status" text NOT NULL,
        "Confidence" double precision NOT NULL,
        "EvidenceCount" integer NOT NULL,
        "ArgumentIdsJson" text NOT NULL,
        "Version" integer NOT NULL,
        "FirstSeenAt" timestamp with time zone NOT NULL,
        "LastUpdatedAt" timestamp with time zone NOT NULL,
        "Tags" character varying(200),
        CONSTRAINT "PK_CommonUnderstandingNodes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "ConvergenceMaps" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "User1Id" character varying(100) NOT NULL,
        "User2Id" character varying(100) NOT NULL,
        "GeneratedAt" timestamp with time zone NOT NULL,
        "LastRefreshedAt" timestamp with time zone NOT NULL,
        "OverallConvergenceScore" double precision NOT NULL,
        "ProfileOverlapJson" text NOT NULL,
        "SharedPropositionIdsJson" text NOT NULL,
        "DisputedPropositionIdsJson" text NOT NULL,
        "DivergencePointsJson" text NOT NULL,
        "ExpansionPathwaysJson" text NOT NULL,
        "EvolutionHistoryJson" text NOT NULL,
        "NarrativeSummary" text NOT NULL,
        CONSTRAINT "PK_ConvergenceMaps" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "PersistedEmergentReports" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "GeneratedAt" timestamp with time zone NOT NULL,
        "IsDeepAnalysis" boolean NOT NULL,
        "TotalArguments" integer NOT NULL,
        "TotalPropositions" integer NOT NULL,
        "TotalEvidenceItems" integer NOT NULL,
        "AverageConfidence" double precision NOT NULL,
        "SettledCount" integer NOT NULL,
        "ContestedCount" integer NOT NULL,
        "BlindspotCount" integer NOT NULL,
        "HarmonyCount" integer NOT NULL,
        "CriticalAssumptionsUntested" integer NOT NULL,
        "BlindspotsSummaryJson" text,
        "HarmoniesSummaryJson" text,
        "ExecutiveSummary" text,
        "FullReportJson" text,
        CONSTRAINT "PK_PersistedEmergentReports" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "SharedItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ItemType" text NOT NULL,
        "ItemReferenceId" character varying(200) NOT NULL,
        "ItemTitle" character varying(300) NOT NULL,
        "SharedByUserId" character varying(100) NOT NULL,
        "SharedWithUserIdsJson" text NOT NULL,
        "Visibility" text NOT NULL,
        "Message" character varying(1000),
        "SharedAt" timestamp with time zone NOT NULL,
        "ReactionsJson" text NOT NULL,
        CONSTRAINT "PK_SharedItems" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "Stakeholders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(150) NOT NULL,
        "Role" character varying(100),
        "Organization" character varying(150),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Stakeholders" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "UserAccounts" (
        "Id" text NOT NULL,
        "Username" character varying(100) NOT NULL,
        "DisplayName" character varying(200) NOT NULL,
        "PasswordHash" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_UserAccounts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "UserConnections" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "InitiatorUserId" character varying(100) NOT NULL,
        "RecipientUserId" character varying(100) NOT NULL,
        "Status" text NOT NULL,
        "InitiatorMessage" character varying(500),
        "InitiatedAt" timestamp with time zone NOT NULL,
        "RespondedAt" timestamp with time zone,
        CONSTRAINT "PK_UserConnections" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "UserProfiles" (
        "Id" text NOT NULL,
        "Name" character varying(200) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastInteractionAt" timestamp with time zone NOT NULL,
        "Stage" character varying(50) NOT NULL,
        "CurrentBeliefSnapshotJson" text,
        "HistoricalSnapshotsJson" text NOT NULL,
        "InteractionsJson" text NOT NULL,
        "AskedQuestionHashesJson" text NOT NULL,
        "ExploredDimensionsJson" text NOT NULL,
        CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "AdjudicationSummaries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ArgumentId" integer NOT NULL,
        "OverallConfidence" double precision NOT NULL,
        "Recommendation" text NOT NULL,
        "ReasoningTrace" text,
        "EvidenceGapsJson" text,
        "ConflictingEvidenceJson" text,
        "NextSteps" text,
        "DetailedNarrative" text,
        "ComputedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AdjudicationSummaries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AdjudicationSummaries_Arguments_ArgumentId" FOREIGN KEY ("ArgumentId") REFERENCES "Arguments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "ArgumentComparisons" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ArgumentAId" integer NOT NULL,
        "ArgumentBId" integer NOT NULL,
        "ConflictingPremisesJson" text,
        "ComplementaryPremisesJson" text,
        "UniqueToPremisesAJson" text,
        "UniqueToPremisesBJson" text,
        "SynthesisNarrative" text,
        "NetDirection" text NOT NULL,
        "NetConfidence" double precision NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ArgumentComparisons" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ArgumentComparisons_Arguments_ArgumentAId" FOREIGN KEY ("ArgumentAId") REFERENCES "Arguments" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ArgumentComparisons_Arguments_ArgumentBId" FOREIGN KEY ("ArgumentBId") REFERENCES "Arguments" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "Claims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ArgumentId" integer NOT NULL,
        "Text" text NOT NULL,
        "ClaimType" character varying(100),
        CONSTRAINT "PK_Claims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Claims_Arguments_ArgumentId" FOREIGN KEY ("ArgumentId") REFERENCES "Arguments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "CommonUnderstandingEdges" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SourceNodeId" integer NOT NULL,
        "TargetNodeId" integer NOT NULL,
        "Relationship" character varying(40) NOT NULL,
        "Strength" double precision NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CommonUnderstandingEdges" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CommonUnderstandingEdges_CommonUnderstandingNodes_SourceNod~" FOREIGN KEY ("SourceNodeId") REFERENCES "CommonUnderstandingNodes" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CommonUnderstandingEdges_CommonUnderstandingNodes_TargetNod~" FOREIGN KEY ("TargetNodeId") REFERENCES "CommonUnderstandingNodes" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "StakeholderPositions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StakeholderId" integer NOT NULL,
        "ArgumentId" integer NOT NULL,
        "Position" text NOT NULL,
        "Reasoning" character varying(2000),
        "AcceptedPremiseIdsJson" text NOT NULL,
        "RejectedPremiseIdsJson" text NOT NULL,
        "IsAnonymous" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_StakeholderPositions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StakeholderPositions_Arguments_ArgumentId" FOREIGN KEY ("ArgumentId") REFERENCES "Arguments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_StakeholderPositions_Stakeholders_StakeholderId" FOREIGN KEY ("StakeholderId") REFERENCES "Stakeholders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "Assumptions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ClaimId" integer NOT NULL,
        "Text" text NOT NULL,
        "IsCritical" boolean NOT NULL,
        "IsSupported" boolean NOT NULL,
        CONSTRAINT "PK_Assumptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Assumptions_Claims_ClaimId" FOREIGN KEY ("ClaimId") REFERENCES "Claims" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "Propositions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ClaimId" integer NOT NULL,
        "Text" text NOT NULL,
        "Status" text NOT NULL,
        "ConfidenceScore" double precision NOT NULL,
        "EvidenceCount" integer NOT NULL,
        "ProvisionalAssessment" character varying(500),
        "ProvisionalConfidence" double precision,
        "SortOrder" integer NOT NULL,
        CONSTRAINT "PK_Propositions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Propositions_Claims_ClaimId" FOREIGN KEY ("ClaimId") REFERENCES "Claims" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "Qualifiers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ClaimId" integer NOT NULL,
        "Text" text NOT NULL,
        "QualifierType" character varying(60),
        CONSTRAINT "PK_Qualifiers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Qualifiers_Claims_ClaimId" FOREIGN KEY ("ClaimId") REFERENCES "Claims" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "Rebuttals" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ClaimId" integer NOT NULL,
        "Text" text NOT NULL,
        "Strength" character varying(20),
        CONSTRAINT "PK_Rebuttals" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Rebuttals_Claims_ClaimId" FOREIGN KEY ("ClaimId") REFERENCES "Claims" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "Syllogisms" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ClaimId" integer NOT NULL,
        "MajorPremise" text NOT NULL,
        "MinorPremise" text NOT NULL,
        "Conclusion" text NOT NULL,
        "InferenceType" text NOT NULL,
        "IsValidForm" boolean NOT NULL,
        "FallaciesDetected" text,
        "SortOrder" integer NOT NULL,
        CONSTRAINT "PK_Syllogisms" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Syllogisms_Claims_ClaimId" FOREIGN KEY ("ClaimId") REFERENCES "Claims" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE TABLE "EvidenceItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PropositionId" integer NOT NULL,
        "Citation" text NOT NULL,
        "SourceUri" character varying(500),
        "DOI" character varying(100),
        "Tier" text NOT NULL,
        "Direction" text NOT NULL,
        "EffectSize" double precision,
        "SampleSize" integer,
        "ReplicationStatus" character varying(40),
        "PublicationYear" integer,
        "AddedBy" character varying(100),
        "AddedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_EvidenceItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EvidenceItems_Propositions_PropositionId" FOREIGN KEY ("PropositionId") REFERENCES "Propositions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_AdjudicationSummaries_ArgumentId" ON "AdjudicationSummaries" ("ArgumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_ArgumentComparisons_ArgumentAId" ON "ArgumentComparisons" ("ArgumentAId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_ArgumentComparisons_ArgumentBId" ON "ArgumentComparisons" ("ArgumentBId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_Assumptions_ClaimId" ON "Assumptions" ("ClaimId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_Claims_ArgumentId" ON "Claims" ("ArgumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_CommonUnderstandingEdges_SourceNodeId" ON "CommonUnderstandingEdges" ("SourceNodeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_CommonUnderstandingEdges_TargetNodeId" ON "CommonUnderstandingEdges" ("TargetNodeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_CommonUnderstandingNodes_NormalizedKey" ON "CommonUnderstandingNodes" ("NormalizedKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_ConvergenceMaps_User1Id_User2Id" ON "ConvergenceMaps" ("User1Id", "User2Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_EvidenceItems_PropositionId" ON "EvidenceItems" ("PropositionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_Propositions_ClaimId" ON "Propositions" ("ClaimId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_Qualifiers_ClaimId" ON "Qualifiers" ("ClaimId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_Rebuttals_ClaimId" ON "Rebuttals" ("ClaimId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_SharedItems_SharedByUserId" ON "SharedItems" ("SharedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_StakeholderPositions_ArgumentId" ON "StakeholderPositions" ("ArgumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_StakeholderPositions_StakeholderId" ON "StakeholderPositions" ("StakeholderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_Syllogisms_ClaimId" ON "Syllogisms" ("ClaimId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_UserAccounts_Username" ON "UserAccounts" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    CREATE INDEX "IX_UserConnections_InitiatorUserId_RecipientUserId" ON "UserConnections" ("InitiatorUserId", "RecipientUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516013154_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260516013154_InitialCreate', '9.0.3');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601033342_AddAiUsageCounters') THEN
    CREATE TABLE "AiUsageCounters" (
        "CounterKey" character varying(200) NOT NULL,
        "RequestCount" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastRequestAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AiUsageCounters" PRIMARY KEY ("CounterKey")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601033342_AddAiUsageCounters') THEN
    CREATE INDEX "IX_AiUsageCounters_LastRequestAt" ON "AiUsageCounters" ("LastRequestAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601033342_AddAiUsageCounters') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260601033342_AddAiUsageCounters', '9.0.3');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "EpistemicProfiles" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "TopicDomain" character varying(100) NOT NULL,
        "EpistemicScore" double precision NOT NULL,
        "VoteAccuracy" double precision NOT NULL,
        "ContributionCount" integer NOT NULL,
        "VoteCount" integer NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_EpistemicProfiles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "ModerationAppeals" (
        "Id" uuid NOT NULL,
        "EntityType" character varying(50) NOT NULL,
        "EntityId" uuid NOT NULL,
        "AppellantUserId" text NOT NULL,
        "Justification" text NOT NULL,
        "Status" character varying(20) NOT NULL,
        "ReviewedByUserId" text,
        "ReviewedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ModerationAppeals" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "ModerationFlags" (
        "Id" uuid NOT NULL,
        "EntityType" character varying(50) NOT NULL,
        "EntityId" uuid NOT NULL,
        "FlaggingUserId" text NOT NULL,
        "Reason" text NOT NULL,
        "Notes" character varying(1000),
        "Status" text NOT NULL,
        "ReviewedByUserId" text,
        "ReviewedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ModerationFlags" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "Moderators" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "TopicDomain" character varying(100),
        "GrantedByUserId" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Moderators" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "SocialPropositions" (
        "Id" uuid NOT NULL,
        "Text" character varying(2000) NOT NULL,
        "Type" integer NOT NULL,
        "SourceUrl" character varying(2048),
        "UserId" text NOT NULL,
        "IsAIGenerated" boolean NOT NULL,
        "IsConfirmed" boolean NOT NULL,
        "Embedding" float4[],
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SocialPropositions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "UserReputations" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "XP" bigint NOT NULL,
        "Rank" character varying(50) NOT NULL,
        "Badges" text[] NOT NULL,
        "CurrentStreak" integer NOT NULL,
        "LongestStreak" integer NOT NULL,
        "LastStreakDate" timestamp with time zone,
        "LastActiveAt" timestamp with time zone NOT NULL,
        "StreakFreezes" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_UserReputations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "Worldviews" (
        "Id" uuid NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Description" character varying(2000),
        "UserId" text NOT NULL,
        "IsPublic" boolean NOT NULL,
        "Tags" text[] NOT NULL,
        "SchwartzValues" text[] NOT NULL,
        "SchwartzVector" float8[] NOT NULL,
        "Embedding" float4[],
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Worldviews" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "XPTransactions" (
        "Id" uuid NOT NULL,
        "UserId" text NOT NULL,
        "Amount" bigint NOT NULL,
        "Reason" character varying(200) NOT NULL,
        "ReferenceEntityId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_XPTransactions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "DebateRooms" (
        "Id" uuid NOT NULL,
        "Title" character varying(300) NOT NULL,
        "Topic" character varying(200) NOT NULL,
        "MotionText" text NOT NULL,
        "MotionPropositionId" uuid,
        "ProponentUserId" text NOT NULL,
        "OpponentUserId" text,
        "JudgeUserIds" text[] NOT NULL,
        "Status" text NOT NULL,
        "Format" text NOT NULL,
        "TimeLimitSeconds" integer NOT NULL,
        "MaxContributionsPerSide" integer NOT NULL,
        "ConcludedAt" timestamp with time zone,
        "ProponentScore" double precision,
        "OpponentScore" double precision,
        "AIRefereeEnabled" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DebateRooms" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DebateRooms_SocialPropositions_MotionPropositionId" FOREIGN KEY ("MotionPropositionId") REFERENCES "SocialPropositions" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "SocialArguments" (
        "Id" uuid NOT NULL,
        "Title" character varying(300) NOT NULL,
        "ClaimPropositionId" uuid NOT NULL,
        "WarrantText" text NOT NULL,
        "ResolutionText" text,
        "Weight" double precision NOT NULL,
        "IsPublic" boolean NOT NULL,
        "IsShadowBanned" boolean NOT NULL,
        "UserId" text NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpvoteCount" integer NOT NULL,
        "DownvoteCount" integer NOT NULL,
        "HotScore" double precision NOT NULL,
        "WilsonScore" double precision NOT NULL,
        "ControversyScore" double precision NOT NULL,
        "IsAIValidated" boolean NOT NULL,
        "AIValidityScore" double precision,
        "AIFallacyFlags" text,
        "Tags" text[] NOT NULL,
        "SchwartzValues" text[] NOT NULL,
        "Embedding" float4[],
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SocialArguments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SocialArguments_SocialPropositions_ClaimPropositionId" FOREIGN KEY ("ClaimPropositionId") REFERENCES "SocialPropositions" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "WorldviewVotes" (
        "Id" uuid NOT NULL,
        "WorldviewId" uuid NOT NULL,
        "UserId" text NOT NULL,
        "Vote" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_WorldviewVotes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_WorldviewVotes_Worldviews_WorldviewId" FOREIGN KEY ("WorldviewId") REFERENCES "Worldviews" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "ArgumentChains" (
        "Id" uuid NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Description" character varying(2000),
        "RootArgumentId" uuid NOT NULL,
        "IsPublic" boolean NOT NULL,
        "UserId" text NOT NULL,
        "Tags" text[] NOT NULL,
        "ArgumentIds" uuid[] NOT NULL,
        "Embedding" float4[],
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ArgumentChains" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ArgumentChains_SocialArguments_RootArgumentId" FOREIGN KEY ("RootArgumentId") REFERENCES "SocialArguments" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "ArgumentLinks" (
        "Id" uuid NOT NULL,
        "SourceArgumentId" uuid NOT NULL,
        "TargetArgumentId" uuid NOT NULL,
        "LinkType" text NOT NULL,
        "Annotation" character varying(500),
        "UserId" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ArgumentLinks" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_ArgumentLinks_NoSelfLoop" CHECK ("SourceArgumentId" <> "TargetArgumentId"),
        CONSTRAINT "FK_ArgumentLinks_SocialArguments_SourceArgumentId" FOREIGN KEY ("SourceArgumentId") REFERENCES "SocialArguments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ArgumentLinks_SocialArguments_TargetArgumentId" FOREIGN KEY ("TargetArgumentId") REFERENCES "SocialArguments" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "ArgumentVotes" (
        "Id" uuid NOT NULL,
        "ArgumentId" uuid NOT NULL,
        "UserId" text NOT NULL,
        "Vote" text NOT NULL,
        "Rationale" text NOT NULL,
        "Comment" character varying(500),
        "EpistemicWeight" double precision NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ArgumentVotes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ArgumentVotes_SocialArguments_ArgumentId" FOREIGN KEY ("ArgumentId") REFERENCES "SocialArguments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "DebateContributions" (
        "Id" uuid NOT NULL,
        "DebateRoomId" uuid NOT NULL,
        "UserId" text NOT NULL,
        "ArgumentId" uuid NOT NULL,
        "Role" text NOT NULL,
        "OrderIndex" integer NOT NULL,
        "FallacyFlags" text,
        "ValidityScore" double precision,
        "AIRefereeComment" character varying(2000),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DebateContributions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DebateContributions_DebateRooms_DebateRoomId" FOREIGN KEY ("DebateRoomId") REFERENCES "DebateRooms" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DebateContributions_SocialArguments_ArgumentId" FOREIGN KEY ("ArgumentId") REFERENCES "SocialArguments" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "SocialArgumentPropositions" (
        "ArgumentId" uuid NOT NULL,
        "PropositionId" uuid NOT NULL,
        "Role" integer NOT NULL,
        "OrderIndex" integer NOT NULL,
        CONSTRAINT "PK_SocialArgumentPropositions" PRIMARY KEY ("ArgumentId", "PropositionId"),
        CONSTRAINT "FK_SocialArgumentPropositions_SocialArguments_ArgumentId" FOREIGN KEY ("ArgumentId") REFERENCES "SocialArguments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SocialArgumentPropositions_SocialPropositions_PropositionId" FOREIGN KEY ("PropositionId") REFERENCES "SocialPropositions" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE TABLE "WorldviewChains" (
        "WorldviewId" uuid NOT NULL,
        "ArgumentChainId" uuid NOT NULL,
        "OrderIndex" integer NOT NULL,
        CONSTRAINT "PK_WorldviewChains" PRIMARY KEY ("WorldviewId", "ArgumentChainId"),
        CONSTRAINT "FK_WorldviewChains_ArgumentChains_ArgumentChainId" FOREIGN KEY ("ArgumentChainId") REFERENCES "ArgumentChains" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_WorldviewChains_Worldviews_WorldviewId" FOREIGN KEY ("WorldviewId") REFERENCES "Worldviews" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX "IX_ArgumentChains_RootArgumentId" ON "ArgumentChains" ("RootArgumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX "IX_ArgumentLinks_SourceArgumentId" ON "ArgumentLinks" ("SourceArgumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX "IX_ArgumentLinks_TargetArgumentId" ON "ArgumentLinks" ("TargetArgumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE UNIQUE INDEX "IX_ArgumentVotes_ArgumentId_UserId" ON "ArgumentVotes" ("ArgumentId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX "IX_DebateContributions_ArgumentId" ON "DebateContributions" ("ArgumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX "IX_DebateContributions_DebateRoomId" ON "DebateContributions" ("DebateRoomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX "IX_DebateRooms_MotionPropositionId" ON "DebateRooms" ("MotionPropositionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE UNIQUE INDEX "IX_EpistemicProfiles_UserId_TopicDomain" ON "EpistemicProfiles" ("UserId", "TopicDomain");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX "IX_ModerationAppeals_AppellantUserId" ON "ModerationAppeals" ("AppellantUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX "IX_ModerationFlags_EntityType_EntityId" ON "ModerationFlags" ("EntityType", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX "IX_ModerationFlags_Status" ON "ModerationFlags" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX "IX_Moderators_UserId_TopicDomain" ON "Moderators" ("UserId", "TopicDomain");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX "IX_SocialArgumentPropositions_PropositionId" ON "SocialArgumentPropositions" ("PropositionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX idx_socialarguments_createdat ON "SocialArguments" ("CreatedAt") WHERE "IsPublic" = true AND "IsShadowBanned" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX idx_socialarguments_hotscore ON "SocialArguments" ("HotScore") WHERE "IsPublic" = true AND "IsShadowBanned" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX idx_socialarguments_wilsonscore ON "SocialArguments" ("WilsonScore") WHERE "IsPublic" = true AND "IsShadowBanned" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX "IX_SocialArguments_ClaimPropositionId" ON "SocialArguments" ("ClaimPropositionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE UNIQUE INDEX "IX_UserReputations_UserId" ON "UserReputations" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX "IX_WorldviewChains_ArgumentChainId" ON "WorldviewChains" ("ArgumentChainId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE UNIQUE INDEX "IX_WorldviewVotes_WorldviewId_UserId" ON "WorldviewVotes" ("WorldviewId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    CREATE INDEX "IX_XPTransactions_UserId" ON "XPTransactions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620054834_AddPhase2SocialEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260620054834_AddPhase2SocialEntities', '9.0.3');
    END IF;
END $EF$;
COMMIT;

