using System.ComponentModel.DataAnnotations;

namespace CommonUnderstanding.Models;

// ─────────────────────────────────────────────
//  Enumerations
// ─────────────────────────────────────────────

public enum PathwayPriority
{
    Low,
    Medium,
    High
}

public enum ExpansionSessionStatus
{
    Active,
    Concluded
}

// ─────────────────────────────────────────────
//  ConvergenceMap — central analytical artifact
// ─────────────────────────────────────────────

/// <summary>
/// Represents the mapped convergence between two users across all three analytical layers:
/// belief profile, argument premises, and shared proposition graph nodes.
/// </summary>
public class ConvergenceMap
{
    public int Id { get; set; }

    [Required, MaxLength(100)]
    public string User1Id { get; set; } = string.Empty;

    [Required, MaxLength(100)]
    public string User2Id { get; set; } = string.Empty;

    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
    public DateTime LastRefreshedAt { get; set; } = DateTime.UtcNow;

    /// <summary>Convergence score from 0 (no overlap) to 100 (identical).</summary>
    public double OverallConvergenceScore { get; set; }

    // ── Profile-level analysis ─────────────────────────────────────────────
    /// <summary>JSON-serialized BeliefComparison produced by BeliefAnalysisService.</summary>
    public string ProfileOverlapJson { get; set; } = "{}";

    // ── Proposition graph-level analysis ──────────────────────────────────
    /// <summary>JSON array of CommonUnderstandingNode IDs that both users' arguments reference.</summary>
    public string SharedPropositionIdsJson { get; set; } = "[]";

    /// <summary>JSON array of CommonUnderstandingNode IDs where the two users hold opposing positions.</summary>
    public string DisputedPropositionIdsJson { get; set; } = "[]";

    // ── Dimensional analysis ───────────────────────────────────────────────
    /// <summary>JSON array of DivergenceDimension objects ranked by gap magnitude.</summary>
    public string DivergencePointsJson { get; set; } = "[]";

    // ── Guided expansion ──────────────────────────────────────────────────
    /// <summary>JSON array of ExpansionPathway objects generated by LLM.</summary>
    public string ExpansionPathwaysJson { get; set; } = "[]";

    // ── History ────────────────────────────────────────────────────────────
    /// <summary>JSON array of ConvergenceSnapshot objects tracking score over time.</summary>
    public string EvolutionHistoryJson { get; set; } = "[]";

    /// <summary>AI-generated narrative summary of the convergence landscape.</summary>
    public string NarrativeSummary { get; set; } = string.Empty;
}

// ─────────────────────────────────────────────
//  DivergenceDimension
// ─────────────────────────────────────────────

/// <summary>
/// A single belief dimension on which the two users hold measurably different positions.
/// Sourced from BeliefSnapshot.Dimensions comparisons.
/// </summary>
public class DivergenceDimension
{
    public string DimensionName { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;

    /// <summary>User 1's position on this dimension [-1.0 to 1.0].</summary>
    public double User1Position { get; set; }

    /// <summary>User 2's position on this dimension [-1.0 to 1.0].</summary>
    public double User2Position { get; set; }

    /// <summary>Absolute gap between positions [0.0 to 2.0].</summary>
    public double Gap { get; set; }

    /// <summary>True if this is a values-level (fundamental) divergence, false if factual.</summary>
    public bool IsValueLevel { get; set; }

    /// <summary>Confidence in User 1's position score.</summary>
    public double User1Confidence { get; set; }

    /// <summary>Confidence in User 2's position score.</summary>
    public double User2Confidence { get; set; }

    /// <summary>AI-suggested common framings that could bridge this dimension.</summary>
    public List<string> BridgingFrames { get; set; } = new();
}

// ─────────────────────────────────────────────
//  ExpansionPathway
// ─────────────────────────────────────────────

/// <summary>
/// An AI-generated pathway for expanding convergence at a specific divergence point.
/// Each pathway anchors on a shared value and provides targeted Socratic questions
/// for each user calibrated to their respective positions.
/// </summary>
public class ExpansionPathway
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string Title { get; set; } = string.Empty;
    public string DivergenceDescription { get; set; } = string.Empty;

    /// <summary>The shared value or moral foundation this pathway leverages.</summary>
    public string SharedValueAnchor { get; set; } = string.Empty;

    /// <summary>A common framing that neither user has yet articulated.</summary>
    public string PotentialCommonFraming { get; set; } = string.Empty;

    /// <summary>Questions targeted to User 1, calibrated to their position.</summary>
    public List<string> QuestionsForUser1 { get; set; } = new();

    /// <summary>Questions targeted to User 2, calibrated to their position.</summary>
    public List<string> QuestionsForUser2 { get; set; } = new();

    public PathwayPriority Priority { get; set; } = PathwayPriority.Medium;

    /// <summary>Expected convergence gain if both users engage this pathway (0-1).</summary>
    public double EstimatedGain { get; set; }
}

// ─────────────────────────────────────────────
//  ConvergenceSnapshot — historical record
// ─────────────────────────────────────────────

/// <summary>
/// A point-in-time record of convergence map state, used to track evolution over time.
/// </summary>
public class ConvergenceSnapshot
{
    public DateTime RecordedAt { get; set; } = DateTime.UtcNow;
    public double ConvergenceScore { get; set; }
    public int SharedPropositionCount { get; set; }
    public int DisputedPropositionCount { get; set; }
    public string? TriggerEvent { get; set; }  // e.g. "ExpansionSession", "NewArgument"
}
