<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>common-understanding-admin-local</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonUnderstanding\CommonUnderstanding.csproj" />
  </ItemGroup>

</Project>