// <auto-generated />
using System;
using CommonUnderstanding.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommonUnderstanding.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516013154_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommonUnderstanding.Models.AdjudicationSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArgumentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConflictingEvidenceJson")
                        .HasColumnType("text");

                    b.Property<string>("DetailedNarrative")
                        .HasColumnType("text");

                    b.Property<string>("EvidenceGapsJson")
                        .HasColumnType("text");

                    b.Property<string>("NextSteps")
                        .HasColumnType("text");

                    b.Property<double>("OverallConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("ReasoningTrace")
                        .HasColumnType("text");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArgumentId")
                        .IsUnique();

                    b.ToTable("AdjudicationSummaries");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Argument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Arguments");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.ArgumentComparison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArgumentAId")
                        .HasColumnType("integer");

                    b.Property<int>("ArgumentBId")
                        .HasColumnType("integer");

                    b.Property<string>("ComplementaryPremisesJson")
                        .HasColumnType("text");

                    b.Property<string>("ConflictingPremisesJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("NetConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("NetDirection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SynthesisNarrative")
                        .HasColumnType("text");

                    b.Property<string>("UniqueToPremisesAJson")
                        .HasColumnType("text");

                    b.Property<string>("UniqueToPremisesBJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArgumentAId");

                    b.HasIndex("ArgumentBId");

                    b.ToTable("ArgumentComparisons");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Assumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSupported")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("Assumptions");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArgumentId")
                        .HasColumnType("integer");

                    b.Property<string>("ClaimType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArgumentId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.CollaborativeSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConcludedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConsolidatedReportJson")
                        .HasColumnType("text");

                    b.Property<string>("ContributedArgumentIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExecutiveSummary")
                        .HasColumnType("text");

                    b.Property<int?>("JointConvergenceMapId")
                        .HasColumnType("integer");

                    b.Property<string>("MergedNodeIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParticipantIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("CollaborativeSessions");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.CommonUnderstandingEdge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("SourceNodeId")
                        .HasColumnType("integer");

                    b.Property<double>("Strength")
                        .HasColumnType("double precision");

                    b.Property<int>("TargetNodeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceNodeId");

                    b.HasIndex("TargetNodeId");

                    b.ToTable("CommonUnderstandingEdges");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.CommonUnderstandingNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArgumentIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedKey");

                    b.ToTable("CommonUnderstandingNodes");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.ConvergenceMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisputedPropositionIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DivergencePointsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvolutionHistoryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpansionPathwaysJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NarrativeSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OverallConvergenceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("ProfileOverlapJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SharedPropositionIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User1Id")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("User2Id")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("User1Id", "User2Id");

                    b.ToTable("ConvergenceMaps");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.EvidenceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AddedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Citation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DOI")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("EffectSize")
                        .HasColumnType("double precision");

                    b.Property<int>("PropositionId")
                        .HasColumnType("integer");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<string>("ReplicationStatus")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropositionId");

                    b.ToTable("EvidenceItems");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.PersistedEmergentReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageConfidence")
                        .HasColumnType("double precision");

                    b.Property<int>("BlindspotCount")
                        .HasColumnType("integer");

                    b.Property<string>("BlindspotsSummaryJson")
                        .HasColumnType("text");

                    b.Property<int>("ContestedCount")
                        .HasColumnType("integer");

                    b.Property<int>("CriticalAssumptionsUntested")
                        .HasColumnType("integer");

                    b.Property<string>("ExecutiveSummary")
                        .HasColumnType("text");

                    b.Property<string>("FullReportJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HarmoniesSummaryJson")
                        .HasColumnType("text");

                    b.Property<int>("HarmonyCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeepAnalysis")
                        .HasColumnType("boolean");

                    b.Property<int>("SettledCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalArguments")
                        .HasColumnType("integer");

                    b.Property<int>("TotalEvidenceItems")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPropositions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PersistedEmergentReports");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.PersistedUserProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AskedQuestionHashesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentBeliefSnapshotJson")
                        .HasColumnType("text");

                    b.Property<string>("ExploredDimensionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HistoricalSnapshotsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InteractionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastInteractionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Proposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProvisionalAssessment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("ProvisionalConfidence")
                        .HasColumnType("double precision");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("Propositions");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Qualifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("QualifierType")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("Qualifiers");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Rebuttal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("Strength")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("Rebuttals");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.SharedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemReferenceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ReactionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SharedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SharedWithUserIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SharedByUserId");

                    b.ToTable("SharedItems");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Stakeholder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Organization")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Stakeholders");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.StakeholderPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcceptedPremiseIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArgumentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reasoning")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RejectedPremiseIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StakeholderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArgumentId");

                    b.HasIndex("StakeholderId");

                    b.ToTable("StakeholderPositions");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Syllogism", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FallaciesDetected")
                        .HasColumnType("text");

                    b.Property<string>("InferenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsValidForm")
                        .HasColumnType("boolean");

                    b.Property<string>("MajorPremise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinorPremise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("Syllogisms");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.UserConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitiatorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("InitiatorUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorUserId", "RecipientUserId");

                    b.ToTable("UserConnections");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.AdjudicationSummary", b =>
                {
                    b.HasOne("CommonUnderstanding.Models.Argument", "Argument")
                        .WithOne("AdjudicationSummary")
                        .HasForeignKey("CommonUnderstanding.Models.AdjudicationSummary", "ArgumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Argument");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.ArgumentComparison", b =>
                {
                    b.HasOne("CommonUnderstanding.Models.Argument", "ArgumentA")
                        .WithMany()
                        .HasForeignKey("ArgumentAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommonUnderstanding.Models.Argument", "ArgumentB")
                        .WithMany()
                        .HasForeignKey("ArgumentBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArgumentA");

                    b.Navigation("ArgumentB");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Assumption", b =>
                {
                    b.HasOne("CommonUnderstanding.Models.Claim", "Claim")
                        .WithMany("Assumptions")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Claim", b =>
                {
                    b.HasOne("CommonUnderstanding.Models.Argument", "Argument")
                        .WithMany("Claims")
                        .HasForeignKey("ArgumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Argument");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.CommonUnderstandingEdge", b =>
                {
                    b.HasOne("CommonUnderstanding.Models.CommonUnderstandingNode", "SourceNode")
                        .WithMany("OutboundEdges")
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommonUnderstanding.Models.CommonUnderstandingNode", "TargetNode")
                        .WithMany("InboundEdges")
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.EvidenceItem", b =>
                {
                    b.HasOne("CommonUnderstanding.Models.Proposition", "Proposition")
                        .WithMany("EvidenceItems")
                        .HasForeignKey("PropositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposition");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Proposition", b =>
                {
                    b.HasOne("CommonUnderstanding.Models.Claim", "Claim")
                        .WithMany("Premises")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Qualifier", b =>
                {
                    b.HasOne("CommonUnderstanding.Models.Claim", "Claim")
                        .WithMany("Qualifiers")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Rebuttal", b =>
                {
                    b.HasOne("CommonUnderstanding.Models.Claim", "Claim")
                        .WithMany("Rebuttals")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.StakeholderPosition", b =>
                {
                    b.HasOne("CommonUnderstanding.Models.Argument", "Argument")
                        .WithMany()
                        .HasForeignKey("ArgumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommonUnderstanding.Models.Stakeholder", "StakeholderRef")
                        .WithMany("Positions")
                        .HasForeignKey("StakeholderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Argument");

                    b.Navigation("StakeholderRef");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Syllogism", b =>
                {
                    b.HasOne("CommonUnderstanding.Models.Claim", "Claim")
                        .WithMany("Syllogisms")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Argument", b =>
                {
                    b.Navigation("AdjudicationSummary");

                    b.Navigation("Claims");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Claim", b =>
                {
                    b.Navigation("Assumptions");

                    b.Navigation("Premises");

                    b.Navigation("Qualifiers");

                    b.Navigation("Rebuttals");

                    b.Navigation("Syllogisms");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.CommonUnderstandingNode", b =>
                {
                    b.Navigation("InboundEdges");

                    b.Navigation("OutboundEdges");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Proposition", b =>
                {
                    b.Navigation("EvidenceItems");
                });

            modelBuilder.Entity("CommonUnderstanding.Models.Stakeholder", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
